[tool.poetry]
name = "explainable-chess-engine"
version = "0.1.0"
description = ""
authors = ["Antoine Déchappe <dechantoine@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
loguru = "^0.7.2"
pandas = "^2.1.4"
jupyter = "^1.0.0"
torch = "^2.1.2"
python-chess = "^1.999"
tqdm = "^4.66.1"
pytest = "^8.1.1"
snakeviz = "^2.2.0"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
