[tool.poetry]
name = "explainable-chess-engine"
version = "0.1.0"
description = ""
authors = ["Antoine Déchappe <dechantoine@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
chess = "^1.10.0"
loguru = "^0.7.2"
pandas = "^2.1.4"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
